src/TheWorld/Models/Stop.cs
using System;

namespace TheWorld.Models
{
    public class Stop
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int Order { get; set; }
        public DateTime Arrival { get; set; }
    }
}

src/TheWorld/Models/Trip.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TheWorld.Models
{
    public class Trip
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime DateCreated { get; set; }
        public string UserName { get; set; }

        public ICollection<Stop> Stops { get; set; }
    }
}

src/TheWorld/Models/WorldContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace TheWorld.Models
{
    public class WorldContext  : DbContext
    {
        public WorldContext()
        {

        }

        public DbSet<Trip> Trips { get; set; }
        public DbSet<Stop> Stops { get; set; }
    }
}

src/TheWorld/ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace TheWorld.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [StringLength(4096, MinimumLength = 10)]
        public string Message { get; set; }
    }
}

src/TheWorld/Controllers/Web/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheWorld.ViewModels;
using TheWorld.Services;
using Microsoft.Extensions.Configuration;

namespace TheWorld.Controllers.Web
{
    public class AppController : Controller
    {
        private IMailService _mailService;
        private IConfigurationRoot _config;

        public AppController(IMailService mailService, IConfigurationRoot config)
        {
            _mailService = mailService;
            _config = config;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact(ContactViewModel model)
        {
            _mailService.SendMail(_config["MailSettings:ToAddress"], "from", "hi", "how's it going?!");

            return View();
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

src/TheWorld/Views/App/About.cshtml
<h2>About</h2>

src/TheWorld/Views/App/Contact.cshtml
@model TheWorld.ViewModels.ContactViewModel
@{
    ViewBag.Title = "Contact Page";
}

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2>Contact</h2>
        <form method="post">
            @if (ViewBag.Message != null)
            {
                <div>@ViewBag.Message</div>
            }
            @*<div asp-validation-summary="ValidationSummary.ModelOnly"></div>*@
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input asp-for="Name" type="text" class="form-control" />
                <span asp-validation-for="Name" class="text-muted"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email">Email</label>
                <input asp-for="Email" type="email" class="form-control" />
                <span asp-validation-for="Email" class="text-muted"></span>
            </div>

            <div class="form-group">
                <label asp-for="Message">Message</label>
                <textarea asp-for="Message" cols="40" rows="4" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-muted"></span>
            </div>
            
            <div class="form-group">
                <a asp-controller="App" asp-action="Index" class="btn btn-default">Cancel</a>
                <input type="submit" value="Send Message" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

src/TheWorld/Views/App/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="row">

    <div class="col-md-6 col-xs-8">
        <h1>The World</h1>
        <p>
            Text to go here
        </p>

        <form>
            <div class="form-group">
                <label>UpDate</label>
                <input class="form-control" />
            </div>
            <div class="form-group">
                <label>Location</label>
                <input class="form-control" />
            </div>
            <div>
                <input type="submit" value="Add" class="btn btn-success" />
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <h1>The Map</h1>
    </div>
</div>

src/TheWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>The World - @ViewBag.Title</title>
    <meta charset="utf-8" />

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootswatch/yeti/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <div id="sidebar">
        <img src="~/img/bmw-e30-wallpaper-8.jpg" alt="headshot" class="headshot" />
        <span>Fong Wong</span>
        <ul class="nav">
            <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
        </ul>
    </div>

    <div id="wrapper">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <button id="sidebarToggle" class="btn btn-primary">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                        </button>
                    </li>
                </ul>
                <a asp-controller="App" asp-action="Index" class="navbar-brand">The World</a>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="glyphicon-save"></i>Save
                        </a>
                    </li>
                    <li>
                        <a href="#" class="btn btn-sm btn-info">
                            <i class="glyphicon-print"></i>Print
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <div id="main" class="container-fluid">
            <div>
                @RenderBody()
            </div>

        </div>

        <div id="footer" class="container-fluid">
            <div class="navbar navbar-inverse navbar-fixed-bottom">
                <h4 class="text-center text-info">&copy; TheWorld Ltd.</h4>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>

    @RenderSection("scripts", false)

</body>
</html>